


///////////////////////////////////////////////////////////////////////////
//NOTE: This file has been automatically generated by Vivado.
///////////////////////////////////////////////////////////////////////////
`timescale 1ps/1ps
package bd_bitflip_axi4stream_vip_1_0_pkg;
import axi4stream_vip_pkg::*;
///////////////////////////////////////////////////////////////////////////
// These parameters are named after the component for use in your verification 
// environment.
///////////////////////////////////////////////////////////////////////////
      parameter bd_bitflip_axi4stream_vip_1_0_VIP_INTERFACE_MODE     = 2;
      parameter bd_bitflip_axi4stream_vip_1_0_VIP_SIGNAL_SET         = 8'b00011011;
      parameter bd_bitflip_axi4stream_vip_1_0_VIP_DATA_WIDTH         = 32;
      parameter bd_bitflip_axi4stream_vip_1_0_VIP_ID_WIDTH           = 0;
      parameter bd_bitflip_axi4stream_vip_1_0_VIP_DEST_WIDTH         = 0;
      parameter bd_bitflip_axi4stream_vip_1_0_VIP_USER_WIDTH         = 0;
      parameter bd_bitflip_axi4stream_vip_1_0_VIP_USER_BITS_PER_BYTE = 0;
      parameter bd_bitflip_axi4stream_vip_1_0_VIP_HAS_TREADY         = 1;
      parameter bd_bitflip_axi4stream_vip_1_0_VIP_HAS_TSTRB          = 0;
      parameter bd_bitflip_axi4stream_vip_1_0_VIP_HAS_TKEEP          = 1;
      parameter bd_bitflip_axi4stream_vip_1_0_VIP_HAS_TLAST          = 1;
      parameter bd_bitflip_axi4stream_vip_1_0_VIP_HAS_ACLKEN         = 0;
      parameter bd_bitflip_axi4stream_vip_1_0_VIP_HAS_ARESETN        = 1;
///////////////////////////////////////////////////////////////////////////


typedef axi4stream_slv_agent #(bd_bitflip_axi4stream_vip_1_0_VIP_SIGNAL_SET, 
                        bd_bitflip_axi4stream_vip_1_0_VIP_DEST_WIDTH,
                        bd_bitflip_axi4stream_vip_1_0_VIP_DATA_WIDTH,
                        bd_bitflip_axi4stream_vip_1_0_VIP_ID_WIDTH,
                        bd_bitflip_axi4stream_vip_1_0_VIP_USER_WIDTH, 
                        bd_bitflip_axi4stream_vip_1_0_VIP_USER_BITS_PER_BYTE,
                        bd_bitflip_axi4stream_vip_1_0_VIP_HAS_ARESETN) bd_bitflip_axi4stream_vip_1_0_slv_t;
      
///////////////////////////////////////////////////////////////////////////
// How to start the verification component
///////////////////////////////////////////////////////////////////////////
//      bd_bitflip_axi4stream_vip_1_0_slv_t  bd_bitflip_axi4stream_vip_1_0_slv;
//      initial begin : START_bd_bitflip_axi4stream_vip_1_0_SLAVE
//        bd_bitflip_axi4stream_vip_1_0_slv = new("bd_bitflip_axi4stream_vip_1_0_slv", `bd_bitflip_axi4stream_vip_1_0_PATH_TO_INTERFACE);
//        bd_bitflip_axi4stream_vip_1_0_slv.start_slave();
//      end

endpackage : bd_bitflip_axi4stream_vip_1_0_pkg
