# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /nfs/nfs2/home/mvidali/E315/P2_EMA/verilog/vsrc/design_fpga/ip/design_fpga_system_ila_0_0/design_fpga_system_ila_0_0.xci
# IP: The module: 'design_fpga_system_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /nfs/nfs2/home/mvidali/E315/P2_EMA/verilog/vsrc/design_fpga/ip/design_fpga_system_ila_0_0/bd_0/bd_d025.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d025 || ORIG_REF_NAME==bd_d025} -quiet] -quiet

# IP: /nfs/nfs2/home/mvidali/E315/P2_EMA/verilog/vsrc/design_fpga/ip/design_fpga_system_ila_0_0/bd_0/ip/ip_0/bd_d025_ila_lib_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d025_ila_lib_0 || ORIG_REF_NAME==bd_d025_ila_lib_0} -quiet] -quiet

# IP: /nfs/nfs2/home/mvidali/E315/P2_EMA/verilog/vsrc/design_fpga/ip/design_fpga_system_ila_0_0/bd_0/ip/ip_1/bd_d025_g_inst_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d025_g_inst_0 || ORIG_REF_NAME==bd_d025_g_inst_0} -quiet] -quiet

# XDC: /nfs/nfs2/home/mvidali/E315/P2_EMA/verilog/vsrc/design_fpga/ip/design_fpga_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_d025_ila_lib_0 || ORIG_REF_NAME==bd_d025_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /nfs/nfs2/home/mvidali/E315/P2_EMA/verilog/vsrc/design_fpga/ip/design_fpga_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_d025_ila_lib_0 || ORIG_REF_NAME==bd_d025_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /nfs/nfs2/home/mvidali/E315/P2_EMA/verilog/vsrc/design_fpga/ip/design_fpga_system_ila_0_0/bd_0/ip/ip_0/bd_d025_ila_lib_0_ooc.xdc

# XDC: /nfs/nfs2/home/mvidali/E315/P2_EMA/verilog/vsrc/design_fpga/ip/design_fpga_system_ila_0_0/bd_0/bd_d025_ooc.xdc

# XDC: /nfs/nfs2/home/mvidali/E315/P2_EMA/verilog/vsrc/design_fpga/ip/design_fpga_system_ila_0_0/design_fpga_system_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_fpga_system_ila_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /nfs/nfs2/home/mvidali/E315/P2_EMA/verilog/vsrc/design_fpga/ip/design_fpga_system_ila_0_0/design_fpga_system_ila_0_0.xci
# IP: The module: 'design_fpga_system_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /nfs/nfs2/home/mvidali/E315/P2_EMA/verilog/vsrc/design_fpga/ip/design_fpga_system_ila_0_0/bd_0/bd_d025.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d025 || ORIG_REF_NAME==bd_d025} -quiet] -quiet

# IP: /nfs/nfs2/home/mvidali/E315/P2_EMA/verilog/vsrc/design_fpga/ip/design_fpga_system_ila_0_0/bd_0/ip/ip_0/bd_d025_ila_lib_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d025_ila_lib_0 || ORIG_REF_NAME==bd_d025_ila_lib_0} -quiet] -quiet

# IP: /nfs/nfs2/home/mvidali/E315/P2_EMA/verilog/vsrc/design_fpga/ip/design_fpga_system_ila_0_0/bd_0/ip/ip_1/bd_d025_g_inst_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d025_g_inst_0 || ORIG_REF_NAME==bd_d025_g_inst_0} -quiet] -quiet

# XDC: /nfs/nfs2/home/mvidali/E315/P2_EMA/verilog/vsrc/design_fpga/ip/design_fpga_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_d025_ila_lib_0 || ORIG_REF_NAME==bd_d025_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /nfs/nfs2/home/mvidali/E315/P2_EMA/verilog/vsrc/design_fpga/ip/design_fpga_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_d025_ila_lib_0 || ORIG_REF_NAME==bd_d025_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /nfs/nfs2/home/mvidali/E315/P2_EMA/verilog/vsrc/design_fpga/ip/design_fpga_system_ila_0_0/bd_0/ip/ip_0/bd_d025_ila_lib_0_ooc.xdc

# XDC: /nfs/nfs2/home/mvidali/E315/P2_EMA/verilog/vsrc/design_fpga/ip/design_fpga_system_ila_0_0/bd_0/bd_d025_ooc.xdc

# XDC: /nfs/nfs2/home/mvidali/E315/P2_EMA/verilog/vsrc/design_fpga/ip/design_fpga_system_ila_0_0/design_fpga_system_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_fpga_system_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
