#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed Sep 21 21:45:00 EDT 2022
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim tb_ema_behav -key {Behavioral:sim_ema:Functional:tb_ema} -tclbatch tb_ema.tcl -protoinst "protoinst_files/bd_d025.protoinst" -protoinst "protoinst_files/design_fpga.protoinst" -protoinst "protoinst_files/bd_bitflip.protoinst" -protoinst "protoinst_files/bd_ema.protoinst" -view /nfs/nfs2/home/mvidali/E315/P2_EMA/verilog/vtests/sim_ema/tb_ema_behav.wcfg -log simulate.log"
xsim tb_ema_behav -key {Behavioral:sim_ema:Functional:tb_ema} -tclbatch tb_ema.tcl -protoinst "protoinst_files/bd_d025.protoinst" -protoinst "protoinst_files/design_fpga.protoinst" -protoinst "protoinst_files/bd_bitflip.protoinst" -protoinst "protoinst_files/bd_ema.protoinst" -view /nfs/nfs2/home/mvidali/E315/P2_EMA/verilog/vtests/sim_ema/tb_ema_behav.wcfg -log simulate.log

