webtalk_init -webtalk_dir /nfs/nfs2/home/mvidali/E315/P2_EMA/vivado_project/vivado_project.sim/sim_ema/behav/xsim/xsim.dir/tb_ema_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Sep 21 21:51:30 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "207618128_1777510348_210665627_004" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "ab5075b4-2e76-4622-917b-b2dc73d3d8d9" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "33e96f9829144c8d9d92ddac47dcbcd2" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "30" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 20.04.5 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3000.000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1130001 ps" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.06_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "129924_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3438812417 -regid "207618128_1777510348_210665627_004" -xml /nfs/nfs2/home/mvidali/E315/P2_EMA/vivado_project/vivado_project.sim/sim_ema/behav/xsim/xsim.dir/tb_ema_behav/webtalk/usage_statistics_ext_xsim.xml -html /nfs/nfs2/home/mvidali/E315/P2_EMA/vivado_project/vivado_project.sim/sim_ema/behav/xsim/xsim.dir/tb_ema_behav/webtalk/usage_statistics_ext_xsim.html -wdm /nfs/nfs2/home/mvidali/E315/P2_EMA/vivado_project/vivado_project.sim/sim_ema/behav/xsim/xsim.dir/tb_ema_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
