#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed Sep 21 19:14:00 EDT 2022
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim tb_bitflip_behav -key {Behavioral:sim_bitflip:Functional:tb_bitflip} -tclbatch tb_bitflip.tcl -protoinst "protoinst_files/bd_bitflip.protoinst" -view /nfs/nfs2/home/mvidali/E315/P2_EMA/verilog/vtests/sim_bitflip/tb_bitflip_behav.wcfg -log simulate.log"
xsim tb_bitflip_behav -key {Behavioral:sim_bitflip:Functional:tb_bitflip} -tclbatch tb_bitflip.tcl -protoinst "protoinst_files/bd_bitflip.protoinst" -view /nfs/nfs2/home/mvidali/E315/P2_EMA/verilog/vtests/sim_bitflip/tb_bitflip_behav.wcfg -log simulate.log

