# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /nfs/nfs2/home/mvidali/E315/P2_EMA/verilog/vsrc/design_fpga/ip/design_fpga_auto_pc_0/design_fpga_auto_pc_0.xci
# IP: The module: 'design_fpga_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /nfs/nfs2/home/mvidali/E315/P2_EMA/verilog/vsrc/design_fpga/ip/design_fpga_auto_pc_0/design_fpga_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_fpga_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /nfs/nfs2/home/mvidali/E315/P2_EMA/verilog/vsrc/design_fpga/ip/design_fpga_auto_pc_0/design_fpga_auto_pc_0.xci
# IP: The module: 'design_fpga_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /nfs/nfs2/home/mvidali/E315/P2_EMA/verilog/vsrc/design_fpga/ip/design_fpga_auto_pc_0/design_fpga_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_fpga_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
