# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: /nfs/nfs2/home/mvidali/E315/P2_EMA/verilog/vsrc/design_fpga/design_fpga.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_fpga || ORIG_REF_NAME==design_fpga} -quiet] -quiet

# IP: /nfs/nfs2/home/mvidali/E315/P2_EMA/verilog/vsrc/design_fpga/ip/design_fpga_processing_system7_0_0/design_fpga_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_fpga_processing_system7_0_0 || ORIG_REF_NAME==design_fpga_processing_system7_0_0} -quiet] -quiet

# IP: /nfs/nfs2/home/mvidali/E315/P2_EMA/verilog/vsrc/design_fpga/ip/design_fpga_axis_bitflip_0_0/design_fpga_axis_bitflip_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_fpga_axis_bitflip_0_0 || ORIG_REF_NAME==design_fpga_axis_bitflip_0_0} -quiet] -quiet

# IP: /nfs/nfs2/home/mvidali/E315/P2_EMA/verilog/vsrc/design_fpga/ip/design_fpga_axi_dma_0_0/design_fpga_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_fpga_axi_dma_0_0 || ORIG_REF_NAME==design_fpga_axi_dma_0_0} -quiet] -quiet

# IP: /nfs/nfs2/home/mvidali/E315/P2_EMA/verilog/vsrc/design_fpga/ip/design_fpga_xbar_0/design_fpga_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_fpga_xbar_0 || ORIG_REF_NAME==design_fpga_xbar_0} -quiet] -quiet

# IP: /nfs/nfs2/home/mvidali/E315/P2_EMA/verilog/vsrc/design_fpga/ip/design_fpga_auto_pc_0/design_fpga_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_fpga_auto_pc_0 || ORIG_REF_NAME==design_fpga_auto_pc_0} -quiet] -quiet

# IP: /nfs/nfs2/home/mvidali/E315/P2_EMA/verilog/vsrc/design_fpga/ip/design_fpga_ps7_0_axi_periph_0/design_fpga_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_fpga_ps7_0_axi_periph_0 || ORIG_REF_NAME==design_fpga_ps7_0_axi_periph_0} -quiet] -quiet

# IP: /nfs/nfs2/home/mvidali/E315/P2_EMA/verilog/vsrc/design_fpga/ip/design_fpga_rst_ps7_0_100M_0/design_fpga_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_fpga_rst_ps7_0_100M_0 || ORIG_REF_NAME==design_fpga_rst_ps7_0_100M_0} -quiet] -quiet

# IP: /nfs/nfs2/home/mvidali/E315/P2_EMA/verilog/vsrc/design_fpga/ip/design_fpga_xbar_1/design_fpga_xbar_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_fpga_xbar_1 || ORIG_REF_NAME==design_fpga_xbar_1} -quiet] -quiet

# IP: /nfs/nfs2/home/mvidali/E315/P2_EMA/verilog/vsrc/design_fpga/ip/design_fpga_auto_us_0/design_fpga_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_fpga_auto_us_0 || ORIG_REF_NAME==design_fpga_auto_us_0} -quiet] -quiet

# IP: /nfs/nfs2/home/mvidali/E315/P2_EMA/verilog/vsrc/design_fpga/ip/design_fpga_auto_us_1/design_fpga_auto_us_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_fpga_auto_us_1 || ORIG_REF_NAME==design_fpga_auto_us_1} -quiet] -quiet

# IP: /nfs/nfs2/home/mvidali/E315/P2_EMA/verilog/vsrc/design_fpga/ip/design_fpga_auto_pc_1/design_fpga_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_fpga_auto_pc_1 || ORIG_REF_NAME==design_fpga_auto_pc_1} -quiet] -quiet

# IP: /nfs/nfs2/home/mvidali/E315/P2_EMA/verilog/vsrc/design_fpga/ip/design_fpga_axi_mem_intercon_0/design_fpga_axi_mem_intercon_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_fpga_axi_mem_intercon_0 || ORIG_REF_NAME==design_fpga_axi_mem_intercon_0} -quiet] -quiet

# IP: /nfs/nfs2/home/mvidali/E315/P2_EMA/verilog/vsrc/design_fpga/ip/design_fpga_axis_ema_0_0/design_fpga_axis_ema_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_fpga_axis_ema_0_0 || ORIG_REF_NAME==design_fpga_axis_ema_0_0} -quiet] -quiet

# IP: /nfs/nfs2/home/mvidali/E315/P2_EMA/verilog/vsrc/design_fpga/ip/design_fpga_axi_dma_1_0/design_fpga_axi_dma_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_fpga_axi_dma_1_0 || ORIG_REF_NAME==design_fpga_axi_dma_1_0} -quiet] -quiet

# IP: /nfs/nfs2/home/mvidali/E315/P2_EMA/verilog/vsrc/design_fpga/ip/design_fpga_system_ila_0_0/design_fpga_system_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_fpga_system_ila_0_0 || ORIG_REF_NAME==design_fpga_system_ila_0_0} -quiet] -quiet

# XDC: /nfs/nfs2/home/mvidali/E315/P2_EMA/verilog/vsrc/design_fpga/design_fpga_ooc.xdc
